# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/doc
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: false
            translatable: false
            blameable: false
            sluggable: false
            loggable: true
            ip_traceable: false
            sortable: false
            softdeleteable: false
            uploadable: false
            reference_integrity: false